language: cpp

matrix:
  include:
    - os: linux
      compiler: i686-w64-mingw32-g++
      env: CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libpng16-16
            - gcc-mingw-w64-i686
            - g++-mingw-w64-i686

script:
  - make CROSS_COMPILE=i686-w64-mingw32- DEBUG=1 -j`nproc` -k heavylog
  - make CROSS_COMPILE=i686-w64-mingw32- -j`nproc` -k standard
